version: "2"
services:
  backend:
    build: ./app
    links:
      - percona-server
    ports:
      - "5000:5000"  
  percona-server:
    image: percona/percona-server:8.0
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root      
    ports:
      - "33068"
    volumes:
      # create volumes for use
      - /var/lib/mysql